/**
 * Auth flow: OAuth callback persistence, injected session build, bootstrap-once behavior.
 */

import {
  jest,
  describe,
  test,
  expect,
  afterEach,
} from '@jest/globals';
import fs from 'fs';
import os from 'os';
import path from 'path';
import http from 'http';
import { fileURLToPath } from 'url';
import { maybeBootstrapSession } from '../extension/src/bootstrap-session.js';
import { writeInjectedSessionFile } from '../scripts/build.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, '..');
const tokenPath = path.join(projectRoot, 'server', 'data', 'tokens.json');

describe('auth and build integration', () => {
  afterEach(() => {
    try {
      fs.unlinkSync(tokenPath);
    } catch {
      /* no file */
    }
    delete process.env.SPOTIFY_CLIENT_ID;
  });

  test('createApp OAuth callback writes tokens.json when code exchange succeeds', async () => {
    process.env.SPOTIFY_CLIENT_ID = 'unit-test-client';

    const exchangeMock = jest.fn().mockResolvedValue({
      access_token: 'access-unit',
      refresh_token: 'refresh-unit',
      expires_in: 3600,
      scope: 'user-read-private',
    });

    await jest.unstable_mockModule('../server/pkce.js', () => ({
      generatePkcePair: () => ({ verifier: 'verifier-unit', challenge: 'challenge-unit' }),
      buildAuthorizeUrl: ({ state }) => `https://accounts.spotify.com/fake?state=${encodeURIComponent(state)}`,
      exchangeCodeForTokens: exchangeMock,
      refreshAccessToken: jest.fn(),
    }));

    const { createApp } = await import('../server/server.js');
    const app = createApp();
    const server = http.createServer(app);

    const port = await new Promise((resolve, reject) => {
      server.listen(0, '127.0.0.1', () => {
        const addr = server.address();
        if (addr && typeof addr === 'object') {
          resolve(addr.port);
        } else {
          reject(new Error('no port'));
        }
      });
      server.on('error', reject);
    });

    try {
      const loginRes = await fetch(`http://127.0.0.1:${port}/login`, { redirect: 'manual' });
      expect(loginRes.status).toBe(302);
      const loc = loginRes.headers.get('location');
      expect(loc).toBeTruthy();
      const u = new URL(loc);
      const state = u.searchParams.get('state');
      expect(state).toBeTruthy();

      const cbRes = await fetch(`http://127.0.0.1:${port}/callback?code=auth-code&state=${encodeURIComponent(state)}`);
      expect(cbRes.ok).toBe(true);

      expect(exchangeMock).toHaveBeenCalledTimes(1);
      expect(fs.existsSync(tokenPath)).toBe(true);
      const saved = JSON.parse(fs.readFileSync(tokenPath, 'utf8'));
      expect(saved.access_token).toBe('access-unit');
      expect(saved.refresh_token).toBe('refresh-unit');
      expect(saved.client_id).toBe('unit-test-client');
      expect(typeof saved.expires_at).toBe('number');
    } finally {
      await new Promise((resolve) => {
        server.close(() => resolve());
      });
      jest.resetModules();
    }
  });

  test('writeInjectedSessionFile generates injected-session.js from fixture tokens.json', () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'randomify-build-'));
    try {
      const fakeRoot = path.join(tmp, 'root');
      const dataDir = path.join(fakeRoot, 'server', 'data');
      const extDir = path.join(fakeRoot, 'extension');
      fs.mkdirSync(dataDir, { recursive: true });
      fs.mkdirSync(extDir, { recursive: true });

      fs.writeFileSync(
        path.join(dataDir, 'tokens.json'),
        JSON.stringify({
          access_token: 'a',
          refresh_token: 'r',
          expires_at: 999,
          client_id: 'cid',
        }),
        'utf8',
      );

      writeInjectedSessionFile(fakeRoot, extDir);
      const outPath = path.join(extDir, 'injected-session.js');
      const text = fs.readFileSync(outPath, 'utf8');
      expect(text).toContain('Auto-generated by build');
      expect(text).toContain('__RANDOMIFY_SESSION__');
      expect(text).toContain('"refresh_token":"r"');
      expect(text).toContain('"client_id":"cid"');
    } finally {
      fs.rmSync(tmp, { recursive: true, force: true });
    }
  });

  test('maybeBootstrapSession imports tokens once and does not overwrite existing refresh token', async () => {
    const STORAGE_KEYS = {
      clientId: 'sts_client_id',
      accessToken: 'sts_access_token',
      refreshToken: 'sts_refresh_token',
      expiresAt: 'sts_expires_at',
    };

    const stored = {};

    async function loadStorage() {
      return { ...stored };
    }

    async function saveStorage(patch) {
      Object.assign(stored, patch);
    }

    globalThis.__RANDOMIFY_SESSION__ = {
      client_id: 'c1',
      access_token: 'a1',
      refresh_token: 'r1',
      expires_at: 111,
    };

    await maybeBootstrapSession({
      loadStorage,
      saveStorage,
      STORAGE_KEYS,
      globalObj: globalThis,
    });

    expect(stored.sts_refresh_token).toBe('r1');
    expect(stored.sts_client_id).toBe('c1');
    expect(globalThis.__RANDOMIFY_SESSION__).toBeUndefined();

    globalThis.__RANDOMIFY_SESSION__ = {
      client_id: 'c2',
      access_token: 'a2',
      refresh_token: 'r2',
      expires_at: 222,
    };

    await maybeBootstrapSession({
      loadStorage,
      saveStorage,
      STORAGE_KEYS,
      globalObj: globalThis,
    });

    expect(stored.sts_refresh_token).toBe('r1');
    expect(stored.sts_client_id).toBe('c1');
    delete globalThis.__RANDOMIFY_SESSION__;
  });
});
