/**
 * First-time setup: collects Spotify Client ID and writes .env
 * (OAuth runs separately via npm run auth).
 */

import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.join(__dirname, '..');
const envPath = path.join(rootDir, '.env');

function question(rl, q) {
  return new Promise((resolve) => {
    rl.question(q, resolve);
  });
}

function writeEnv(clientId, clientSecret) {
  const lines = [
    '# Generated by server/setup.js. Do not commit this file.',
    `SPOTIFY_CLIENT_ID=${clientId}`,
    clientSecret ? `SPOTIFY_CLIENT_SECRET=${clientSecret}` : '# SPOTIFY_CLIENT_SECRET optional for PKCE public clients',
    'PORT=8888',
    '',
  ];
  fs.writeFileSync(envPath, lines.join('\n'), 'utf8');
}

async function main() {
  console.log('');
  console.log('Randomify: setup');
  console.log('---------------------------');
  console.log('');
  console.log('1. Open the Spotify Developer Dashboard:');
  console.log('   https://developer.spotify.com/dashboard');
  console.log('');
  console.log('2. Create an app. Add Redirect URI (exactly):');
  console.log('   http://localhost:8888/callback');
  console.log('');
  console.log('3. Copy the Client ID (Client Secret is optional for PKCE).');
  console.log('');

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  const clientId = (await question(rl, 'Paste your Spotify Client ID: ')).trim();
  if (!clientId) {
    console.error('Client ID is required.');
    rl.close();
    process.exit(1);
  }

  const clientSecret = (
    await question(rl, 'Paste your Client Secret (optional). Press Enter to skip: ')
  ).trim();

  writeEnv(clientId, clientSecret);
  rl.close();

  console.log('');
  console.log(`Saved credentials to ${envPath}`);
  console.log('');
  console.log('Next: run npm run auth (browser opens for Spotify login; extension builds when done).');
  console.log('');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
